baseURL = 'https://blog.sungardajames.com/'
locale = 'en-us'
title = 'coffee_thoughts'
theme = ['PaperMod']
copyright = "© 2026 James Sungarda"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
  math = true

  ShowReadingTime = true

  [params.homeInfoParams]
    Title = "Hello World!"
    Content = """These are my personal essays/notes/others mostly on tech, economics, philosophy, and literature.  
    If I find them interesting enough, I will post them here."""

  [[params.socialIcons]]
    name = "Email"
    url = "mailto:mail@sungardajames.com"

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/invalidcode232"

  # [[params.socialIcons]]
  #   name = "LinkedIn"
  #   url = "https://www.linkedin.com/in/james-sungarda"
  
[caches]
    [caches.images]
        dir = ':cacheDir/images'

[menu]
    [[menu.main]]
        name ="home/"
        url = "/"
        weight = 1
    [[menu.main]]
        name ="posts/"
        url = "/posts/"
        weight = 2
    [[menu.main]]
        name = "about/"
        url = "/about/"
        weight = 3

[services]
  [services.googleAnalytics]
    id = 'G-ZBDR2S35X7'
